#!/usr/bin/env python3
"""Turn a microWakeWord model (.tflite + its .json manifest) into WakeModel.h.

    python3 tools/wake/make_model_header.py tools/wake/models/hey_jarvis.tflite
    python3 tools/wake/make_model_header.py path/to/hey_agora.tflite   # after training
    python3 tools/wake/make_model_header.py --check                    # is WakeModel.h current?

The manifest is the .json beside the .tflite (same stem) in the format the
esphome/micro-wake-word-models repo uses. Everything the firmware needs to know
about the model comes from here: the phrase shown in the UI, the probability
cutoff, the sliding window, the feature step, and the arena size. The bytes go
into flash as an aligned const array; TFLite Micro reads the flatbuffer in
place, so nothing is copied to RAM.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / 'WakeModel.h'
DEFAULT_MODEL = Path(__file__).resolve().parent / 'models' / 'hey_jarvis.tflite'
MARKER = '// Source: '


def c_string(text: str) -> str:
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render(model: Path) -> str:
    manifest_path = model.with_suffix('.json')
    if not manifest_path.exists():
        sys.exit(f'error: {manifest_path} not found; microWakeWord models ship with a .json manifest')
    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    micro = manifest.get('micro') or {}
    phrase = manifest.get('wake_word') or model.stem.replace('_', ' ').title()
    # The name the transcript may start with, e.g. "Hey Jarvis" -> "jarvis".
    name = re.sub(r'[^a-z0-9 ]', '', phrase.lower()).split()[-1]
    cutoff = float(micro.get('probability_cutoff', 0.97))
    window = int(micro.get('sliding_window_size', 5))
    step = int(micro.get('feature_step_size', 10))
    arena = int(micro.get('tensor_arena_size', 30000))
    if step != 10:
        sys.exit(f'error: feature_step_size is {step} ms; the firmware frontend runs 10 ms steps')
    if not 0 < cutoff < 1 or not 1 <= window <= 32:
        sys.exit('error: probability_cutoff or sliding_window_size looks wrong in the manifest')

    data = model.read_bytes()
    if data[4:8] != b'TFL3':
        sys.exit(f'error: {model} is not a TFLite flatbuffer')
    rows = []
    for i in range(0, len(data), 16):
        rows.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',')

    try:
        source = model.resolve().relative_to(ROOT)
    except ValueError:
        source = model.name
    return '\n'.join([
        '#pragma once',
        '',
        '// GENERATED by tools/wake/make_model_header.py. Do not edit by hand;',
        '// rerun the script with a new .tflite (and its .json) to swap the wake word.',
        f'{MARKER}{source} ({len(data)} bytes)',
        f'// Model: {manifest.get("author", "unknown author")}, version {manifest.get("version", "?")}.',
        '// Include from exactly one .cpp (Wake.cpp); everything else asks wakeWord.',
        '',
        '#include <stddef.h>',
        '#include <stdint.h>',
        '',
        f'constexpr char WAKE_MODEL_PHRASE[] = {c_string(phrase)};',
        f'constexpr char WAKE_MODEL_NAME[] = {c_string(name)};',
        f'constexpr float WAKE_MODEL_CUTOFF = {cutoff:.3f}f;',
        f'constexpr uint8_t WAKE_MODEL_WINDOW = {window};',
        f'constexpr uint8_t WAKE_MODEL_STEP_MS = {step};',
        f'constexpr size_t WAKE_MODEL_ARENA = {arena};',
        f'constexpr size_t WAKE_MODEL_SIZE = {len(data)};',
        '',
        '// 16-byte aligned: TFLite Micro reads the flatbuffer in place from flash.',
        'alignas(16) static const uint8_t WAKE_MODEL_DATA[] = {',
        *rows,
        '};',
        '',
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('model', nargs='?', type=Path, help='the .tflite file (default: the shipped Hey Jarvis)')
    parser.add_argument('--check', action='store_true', help='exit 1 if WakeModel.h does not match the model')
    args = parser.parse_args()

    model = args.model
    if model is None and args.check and HEADER.exists():
        # Check against whichever model the header says it came from.
        for line in HEADER.read_text(encoding='utf-8').splitlines():
            if line.startswith(MARKER):
                model = ROOT / line[len(MARKER):].split(' (')[0]
                break
    model = model or DEFAULT_MODEL
    if not model.exists():
        sys.exit(f'error: {model} not found')

    text = render(model)
    if args.check:
        current = HEADER.read_text(encoding='utf-8') if HEADER.exists() else ''
        if current != text:
            print('WakeModel.h is stale; run python3 tools/wake/make_model_header.py', file=sys.stderr)
            return 1
        print('WakeModel.h is current')
        return 0
    HEADER.write_text(text, encoding='utf-8')
    print(f'wrote {HEADER.relative_to(ROOT)} from {model.name}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
