#!/usr/bin/env python3
"""Assemble web/ into the single page the board serves, and emit Page.h.

    python3 web/build.py          # writes ../Page.h (gzip, PROGMEM)
    python3 web/build.py --check  # exit 1 if Page.h is stale

index.html references styles.css and js/*.js the way a normal site would;
here they are inlined in order so the board serves one self-contained
document. tools/preview.py calls assemble() so the preview is the same
bytes the firmware ships, just not compressed.
"""
from __future__ import annotations

import gzip
import hashlib
import re
import sys
from pathlib import Path

WEB = Path(__file__).resolve().parent
PAGE_H = WEB.parent / 'Page.h'
SCRIPT_TAG = re.compile(r'<script src="([^"]+)"></script>')
STYLE_TAG = re.compile(r'<link rel="stylesheet" href="([^"]+)">')


def sources() -> list[Path]:
    """Every file that feeds the page, for staleness checks."""
    index = WEB / 'index.html'
    html = index.read_text(encoding='utf-8')
    found = [index]
    found += [WEB / m.group(1) for m in STYLE_TAG.finditer(html)]
    found += [WEB / m.group(1) for m in SCRIPT_TAG.finditer(html)]
    return found


def assemble() -> str:
    html = (WEB / 'index.html').read_text(encoding='utf-8')
    html = STYLE_TAG.sub(lambda m: '<style>' + (WEB / m.group(1)).read_text(encoding='utf-8') + '</style>', html)

    # Consecutive script tags collapse into one block so the board serves a
    # single script, exactly as the page did before it was split up.
    scripts = SCRIPT_TAG.findall(html)
    if scripts:
        body = ''.join((WEB / s).read_text(encoding='utf-8') for s in scripts)
        first = SCRIPT_TAG.search(html)
        html = html[:first.start()] + '<script>' + body + '</script>' + SCRIPT_TAG.sub('', html[first.end():])
        # Dropping the later tags leaves their line breaks behind; tidy those.
        html = re.sub(r'</script>\n(\n)+', '</script>\n', html)
    return html


def digest(html: str) -> str:
    return hashlib.sha256(html.encode('utf-8')).hexdigest()


def render_header(html: str) -> str:
    raw = html.encode('utf-8')
    # mtime=0 keeps the output reproducible, so Page.h only changes when web/ does.
    packed = gzip.compress(raw, compresslevel=9, mtime=0)
    assert gzip.decompress(packed) == raw
    rows = []
    for i in range(0, len(packed), 16):
        rows.append('  ' + ', '.join(f'0x{b:02x}' for b in packed[i:i + 16]) + ',')
    return (
        '#pragma once\n'
        '\n'
        '// GENERATED by web/build.py from web/ -- do not edit by hand.\n'
        '// Self-contained UI: no network fonts, CDNs, or client-side dependencies.\n'
        f'// source sha256: {digest(html)}\n'
        f'// {len(raw)} bytes of HTML, {len(packed)} bytes gzipped.\n'
        '\n'
        '#include <pgmspace.h>\n'
        '\n'
        f'constexpr size_t INDEX_HTML_GZ_LEN = {len(packed)};\n'
        'static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n'
        + '\n'.join(rows) + '\n'
        '};\n'
    )


def current_digest() -> str | None:
    if not PAGE_H.exists():
        return None
    m = re.search(r'^// source sha256: ([0-9a-f]{64})$', PAGE_H.read_text(encoding='utf-8'), re.M)
    return m.group(1) if m else None


def main(argv: list[str]) -> int:
    html = assemble()
    if '--check' in argv:
        if current_digest() == digest(html):
            print('Page.h is up to date.')
            return 0
        print('Page.h is stale: run python3 web/build.py', file=sys.stderr)
        return 1
    out = render_header(html)
    PAGE_H.write_text(out, encoding='utf-8')
    packed = int(re.search(r'INDEX_HTML_GZ_LEN = (\d+)', out).group(1))
    print(f'Wrote {PAGE_H.name}: {len(html.encode("utf-8"))} bytes HTML -> {packed} bytes gzip')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
